# <center> 26th Feb Assignment

In [12]:
# Consider the below code to answer further questions:
import pandas as pd    
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(list_)

# Q1:-  Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Ans1 :- Yes, there is a difference in the data type of the variables list_ and array_list. The list_ variable is a Python list object that contains string values, while array_list is a NumPy array object that contains the same string values but with a data type of numpy.str_.

In [17]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [21]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [22]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3:- Considering the following changes in the variable, array_list:

In [23]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans3:- Yes, The variables in array_list will have data type as int 64

In [25]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Consider the below code to answer further questions:

In [27]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape

(ii) size

shape function shows the dimension of num_array. It returns a tuple of integers that represent the shape of the array. as the num_array is having 2 rows and 3 columns.

In [30]:
num_array.size

6

size shows the number of elements in an array

In [31]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [36]:
# Ans 3:- 

import numpy as np

arr = np.zeros((3,3))

arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [40]:
import numpy as np

arr2 = np.eye(5,5)

print(arr2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# <Center> End of Assignment